spring:
  application.name: api-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: car-service
          uri: lb://CAR-SERVICE
          predicates:
            - Path=/cars/**

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/users/**, /register

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: message-service
          uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/sender/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: keycloak
            client-id: api-client
            client-secret: kfECkllyhRk4LZpxJYB56ibT54PajiFu
            authorization-grant-type: authorization_code
            redirect-uri: "http://api-gateway:8000/login/oauth2/code/{registrationId}"
            scope: openid, roles, profile
        provider:
          keycloak:
              issuer-uri: http://keycloak:8080/realms/car-repair-realm

eureka:
  client:
    register-with-eureka: false

logging:
  level:
    root: INFO
