spring:
  application.name: api-gateway
  cloud:
    gateway:
      routes:
        - id: car-service
          uri: lb://CAR-SERVICE
          predicates:
            - Path=/cars, /cars/**
          filters:
            - TokenRelay=

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/users/**, /register
          filters:
            - TokenRelay=
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: keycloak
            client-id: api-client
            client-secret: kfECkllyhRk4LZpxJYB56ibT54PajiFu
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid, roles, profile
        provider:
          keycloak:
              issuer-uri: http://localhost:8083/realms/car-repair-realm

eureka:
  client:
    register-with-eureka: false

logging:
  level:
    root: INFO
