
version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: keycloakDb
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - keycloak_network
  kc:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak
    command:
      - start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: keycloakDb
      KC_DB_USERNAME: my_user
      KC_DB_PASSWORD: my_password
      KEYCLOAK_HOSTNAME: localhost
      KEYCLOAK_ADMIN: kc_admin
      KEYCLOAK_ADMIN_PASSWORD: kc_password
    ports:
      - "8083:8080"
    volumes:
      - keycloak_data:/var/lib/keycloak/data
    depends_on:
      - db
    networks:
      - keycloak_network

networks:
  keycloak_network:

volumes:
  keycloak_data: